name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run RDP Setup Script
        env:
          TAILSCALE_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          powershell -ExecutionPolicy Unrestricted -File .\setup.ps1
          
